### ISSUE TITLE
What license is this app under?

### ISSUE THREAD

**Issue by richienyhus** [devaspot/chat#1]
The only license info says "Attribution-NonCommercial 3.0 Unported", is that it?

**Comment by 5HT** [comment]
The Licence is MIT

**Comment by richienyhus** [comment]
Nice!

Has a GCI2013 student already contacted you about this?

**Comment by 5HT** [comment]
Not yet. With pleasure will describe my vision and be a mentor.

**Comment by richienyhus** [comment]
The student's work has already been published, so we have to wait for them to fix up the Licence as they are doing a new task now.

The student's task for chat was to create a package manager recipe so we can add Chat to HaikuDepot, this also means that Chat will be fully compatible with Haiku R1B1 when it comes out in a few months.

**Comment by 5HT** [comment]
Chat originally was designed as Default Small Chat Application for Haiku with Video Chat capabilities. Later the decision was superseded in favor to 10MB Caya for unknown reason.

**Comment by poxip** [comment]
Ok, I'll correct it.

/edit: corrected

**Comment by 5HT** [comment]
Could you please show your fork ?

**Comment by richienyhus** [comment]
His change was just for our HaikuPorts database: http://bb.haikuports.org/haikuports/pull-request/126/haiku-chat-recipe-corrected/diff

The only possible change here would be to add a Licence file containing the terms of the MIT Licence, but that is not so important now.

I'll close the ticket, since the it is only a HaikuPorts issue now.
